### ISSUE TITLE
Freecam won't stay enabled when hosting LAN worlds with Lunar Client

### ISSUE THREAD

**Issue by Itznicd** [MinecraftFreecam/Freecam#206] opened 2024-05-01 22:26 UTC
### Description of the issue

The host who is hosting a LAN world (multiplayer) cannot use it

### Expected behavior

I expected to be able to use it

### Steps to reproduce

1. Open a singleplayer world
2. open to LAN
3. try to freecam

### How prevalent is the issue?

everytime

### Freecam version

1.2.4

### Are you using "Modrinth Edition"?

No

### Minecraft version

1.20.5

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by MattSturgeon** [comment] 2024-05-03 10:58
Do you have any non-default freecam options or other mods installed? I'm unable to reproduce the issue. I'm still able to activate freecam even when hosting a LAN world.

If I _join_ a LAN world using Freecam _Modrinth Edition_ or with the new "multiplayer options" _restrictions_ enabled, then freecam is restricted as-per any other multiplayer server.

**Comment by Itznicd** [comment] 2024-05-03 11:07
nope, I am playing on lunar client though, I could send a video of the
issue or something when I get home

**Comment by MattSturgeon** [comment] 2024-05-03 14:43
I wasn't aware that Freecam could be installed on Lunar CLient... To quote their [FAQ](https://www.lunarclient.com/faq):

> You can only use mods that are provided by the client, you may not use your own mods.

Still, any more detail or videos you provide would be appreciated.

**Comment by hashalite** [comment] 2024-05-03 19:32
I was able to reproduce on 1.2.4 Modrinth edition (not regular) for 1.20.5. Steps followed:
1. Created new world
2. Opened LAN
3. NoClip is restricted (I'm assuming this is what you mean by "not working")

**Comment by Itznicd** [comment] 2024-05-03 20:13
Heres a video: https://streamable.com/0a0pbz
Ive figured out it only does this with lunar client not normal minecraft

**Comment by Itznicd** [comment] 2024-05-03 20:14
My friend who joins the world can use it but the host cant

**Comment by MattSturgeon** [comment] 2024-05-03 20:26
> [Heres a video](https://streamable.com/0a0pbz)

Thanks, that is helpful.

It looks like Freecam is being disabled immediately after it is enabled, perhaps by our "disable next tick" flag, usually reserved for "disable on damage" and similar features.

IIRC, disable next tick is also set by the new multiplayer restriction options added in 1.2.4. Can you confirm you didn't have this issue on older Freecam versions, even with Lunar Client?

Looking at your video, @hashalite's [comment](https://github.com/MinecraftFreecam/Freecam/issues/206#issuecomment-2093646219) appears to be a separate issue, possibly with a similar underlying cause.

This may be related to the subtle difference between `isSingleplayer` and `hasSingleplayerServer` he pointed out to me on discord.

One of us will update this thread when we have chance to make a test build.

**Comment by hashalite** [comment] 2024-05-03 20:39
> Heres a video: https://streamable.com/0a0pbz Ive figured out it only does this with lunar client not normal minecraft

Would you mind trying with "Disable on Damage" turned off?

**Comment by Itznicd** [comment] 2024-05-03 20:45
> > Heres a video: https://streamable.com/0a0pbz Ive figured out it only does this with lunar client not normal minecraft
> 
> Would you mind trying with "Disable on Damage" turned off?

hasalite turning off disable on damage doesnt fix it

**Comment by Itznicd** [comment] 2024-05-03 20:49
> > [Heres a video](https://streamable.com/0a0pbz)
> 
> Thanks, that is helpful.
> 
> It looks like Freecam is being disabled immediately after it is enabled, perhaps by our "disable next tick" flag, usually reserved for "disable on damage" and similar features.
> 
> IIRC, disable next tick is also set by the new multiplayer restriction options added in 1.2.4. Can you confirm you didn't have this issue on older Freecam versions, even with Lunar Client?
> 
> Looking at your video, @hashalite's [comment](https://github.com/MinecraftFreecam/Freecam/issues/206#issuecomment-2093646219) appears to be a separate issue, possibly with a similar underlying cause.
> 
> This may be related to the subtle difference between `isSingleplayer` and `hasSingleplayerServer` he pointed out to me on discord.
> 
> One of us will update this thread when we have chance to make a test build.

this also happens on older versions as i just tested the 1.20.4 version on 1.20.4 and it does the same thing
Is there anything else you need me to do to help? I just really want to be able to use it

**Comment by Itznicd** [comment] 2024-05-03 20:53
> > [Heres a video](https://streamable.com/0a0pbz)
> 
> Thanks, that is helpful.
> 
> It looks like Freecam is being disabled immediately after it is enabled, perhaps by our "disable next tick" flag, usually reserved for "disable on damage" and similar features.
> 
> IIRC, disable next tick is also set by the new multiplayer restriction options added in 1.2.4. Can you confirm you didn't have this issue on older Freecam versions, even with Lunar Client?
> 
> Looking at your video, @hashalite's [comment](https://github.com/MinecraftFreecam/Freecam/issues/206#issuecomment-2093646219) appears to be a separate issue, possibly with a similar underlying cause.
> 
> This may be related to the subtle difference between `isSingleplayer` and `hasSingleplayerServer` he pointed out to me on discord.
> 
> One of us will update this thread when we have chance to make a test build.

this also happens on older versions as i just tested the 1.19.2 version on 1.19.2 and it does the same thing
Is there anything else you need me to do to help? I just really want to be able to use it

**Comment by hashalite** [comment] 2024-05-03 23:11
@Itznicd A test build containing a fix for this has been posted here: https://github.com/MinecraftFreecam/Freecam/pull/207

**Comment by Itznicd** [comment] 2024-05-03 23:12
> @Itznicd A test build containing a fix for this has been posted here: #207

thank you so much

**Comment by MattSturgeon** [comment] 2024-05-03 23:31
Please let us know if you run into any issues with the fixed version. In particular, Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited. Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.

**Comment by Itznicd** [comment] 2024-05-04 01:15
> Please let us know if you run into any issues with the fixed version. In particular:
> 
> * Does the fix actually work?
> * Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited.
> * Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.
> * Freecam shouldn't randomly disconnect (unless you hit the keybind, take damage, exit the world, etc).

Wdym fixed version?

**Comment by Itznicd** [comment] 2024-05-04 01:33
> Please let us know if you run into any issues with the fixed version. In particular:
> 
> * Does the fix actually work?
> * Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited.
> * Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.
> * Freecam shouldn't randomly disconnect (unless you hit the keybind, take damage, exit the world, etc).

did you fix it or something im confused?

**Comment by Itznicd** [comment] 2024-05-04 03:57
> Please let us know if you run into any issues with the fixed version. In particular:
> 
> * Does the fix actually work?
> * Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited.
> * Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.
> * Freecam shouldn't randomly disconnect (unless you hit the keybind, take damage, exit the world, etc).

will it be fixed in the next official version? Or will i need to download a custom fixed file like i did this time every time the game updates?

**Comment by Itznicd** [comment] 2024-05-04 04:37
> Please let us know if you run into any issues with the fixed version. In particular:
> 
> * Does the fix actually work?
> * Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited.
> * Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.
> * Freecam shouldn't randomly disconnect (unless you hit the keybind, take damage, exit the world, etc).

It works! please add this fix into all future versions 🙏

**Comment by MattSturgeon** [comment] 2024-05-22 22:03
> will it be fixed in the next official version?

The fix should make it into the next Freecam release, yes.



> > Please let us know if you run into any issues with the fixed version. In particular:
> > 
> > * Does the fix actually work?
> > * Freecam should be disabled when loading into a world, regardless of what state it was in when you last exited.
> > * Tripods (etc) should also be saved correctly, even if you exit a world with a tripod open.
> > * Freecam shouldn't randomly disconnect (unless you hit the keybind, take damage, exit the world, etc).
> 
> It works! please add this fix into all future versions 🙏

Thanks for confirming it works. Could you also try and test out some of the potential issues outlined above if you have chance?

**Closed** 2024-06-03 18:30 UTC
Labels: bug, compatibility
