### ISSUE TITLE
Switching dimensions while freecam is enabled crashes the game

### ISSUE THREAD

**Issue by hashalite** [MinecraftFreecam/Freecam#170] opened 2024-02-05 07:54 UTC
[williamodavis](https://www.curseforge.com/members/williamodavis) on CurseForge reports:

> Found a bug, if you go into a nether portal, activate freecam, and then wait, your game will crash the second you switch dimensions

**Comment by hATrayflood** [comment] 2024-02-20 11:06
I have a similar problem.
game crashes when just only enabling freecam, by default settings.

minecraft version: fabric-loader-0.15.6-1.20.4

mods
```
advanced-xray-fabric-84.0.0.jar
c2me-fabric-mc1.20.4-0.2.0+alpha.11.40.jar
cloth-config-13.0.121-fabric.jar
CocoaInput-1.20.2-fabric-4.0.10-PREVIEW2.jar
continuity-3.0.0-beta.4+1.20.2.jar
dynamic-fps-3.3.3+minecraft-1.20.0.jar
enhancedblockentities-0.9.1+1.20.2.jar
entityculling-fabric-1.6.3.1-mc1.20.4.jar
fabric-api-0.95.1+1.20.4.jar
ferritecore-6.0.3-fabric.jar
freecam-fabric-modrinth-1.2.1.1+1.20.jar
ImmediatelyFast-Fabric-1.2.8+1.20.4.jar
indium-1.0.28+mc1.20.4.jar
iris-mc1.20.4-1.6.14.jar
Jade-1.20.4-fabric-13.3.1.jar
krypton-0.2.6.jar
lazydfu-0.1.3.jar
litematica-fabric-1.20.4-0.17.0.jar
lithium-fabric-mc1.20.4-0.12.1.jar
malilib-fabric-1.20.4-0.18.0.jar
memoryleakfix-forge-1.17+-1.1.5.jar
minihud-fabric-1.20.4-0.30.0.jar
modmenu-9.0.0.jar
moreculling-1.20.4-0.22.1.jar
reeses_sodium_options-1.7.0+mc1.20.2-build.97.jar
sodium-extra-0.5.3+mc1.20.2-build.114.jar
sodium-fabric-mc1.20.3-0.5.5.jar
starlight-1.1.3+fabric.f5dcd1a.jar
your-reputation-0.2.5+jade.1.20.jar
```

stack trace
```
Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:499)
	at net.minecraft.class_638.method_32124(class_638.java:260)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:256)
	at net.minecraft.class_310.method_1574(class_310.java:2011)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4262
	at net.xolt.freecam.config.CollisionWhitelist.<clinit>(CollisionWhitelist.java:10)
	at net.minecraft.class_4970$class_4971.handler$bfa000$freecam$onGetCollisionShape(class_4970.java:2945)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:219)
	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.doesBoxCollideWithBlocks(LithiumEntityCollisions.java:49)
	at net.minecraft.class_1937.method_8587(class_1937.java:3565)
	at net.minecraft.class_1657.method_52558(class_1657.java:459)
	at net.minecraft.class_1657.method_7318(class_1657.java:422)
	at net.minecraft.class_1657.method_5773(class_1657.java:332)
	at net.minecraft.class_742.method_5773(class_742.java:59)
	at net.minecraft.class_746.method_5773(class_746.java:218)
	at net.minecraft.class_638.method_18646(class_638.java:277)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4262
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 23 more
```

[crash-2024-02-20_19.53.11-client.txt.zip](https://github.com/MinecraftFreecam/Freecam/files/14343249/crash-2024-02-20_19.53.11-client.txt.zip)

to avoid crash:
change freecam options
- Collision Options
  - Ignore Transparent Blocks
    - change to No
  - Ignore Openable Blocks
    - change to No

![image](https://github.com/MinecraftFreecam/Freecam/assets/2013010/08db4708-cf9b-49ee-b201-2a17865dbfdd)

**Comment by MattSturgeon** [comment] 2024-02-20 11:16
@hATrayflood you're using Freecam 1.2.1.1+1.20 with MC 1.20.4. That Freecam version was built for MC 1.20.2, and is incompatible with 1.20.3+. Try using [Freecam 1.2.3](https://modrinth.com/mod/freecam/versions?g=1.20.4) instead.

**Comment by MattSturgeon** [comment] 2024-02-28 12:15
I can't reproduce this issue on the following versions:

- 1.2.0 (fabric)
- 1.2.3 (fabric)
- 1.2.3 (neoforge)

 I suspect it may be caused by mismatched Minecraft versions or perhaps a mod confilct. Marking as invalid for now.

**Closed by MattSturgeon** 2024-02-28 12:15 UTC
Labels: bug
