### ISSUE TITLE
[1.21-fabric] A way to force sync configs between server and config

### ISSUE THREAD

**Issue by jinkhya** [MinecraftFreecam/Freecam#226] opened 2024-06-16 14:24 UTC
### Description of the feature

Hello ! 

I understand how useful this mod is but I also see how much of an advantage it can give compared to people not using it on a same server.
So my suggestion is this : Could it be possible to have a server version that would force sync the config on clients to prevent colliding through blocks. That way it still allows builders to take a step back and look at their creations, and prevent people from scanning underground for dungeons, exposed diamonds etc. 
Unless there's another way to do it ofc. 

Best regards,
Jin

### Why is this useful?

It would solve the problem of people using it to scan underground for goodies.

### Freecam version

1.3.0-beta1

**Comment by MattSturgeon** [comment] 2024-06-16 16:41
This is a difficult and somewhat controversial problem to solve.

In an ideal world, it's down to servers to decide what is allowed, and players to use their installed mods appropriately.

I appreciate from a server's perspective this is less than ideal, because you are relying on the honour system.

You can state in your server policies that users should disable Freecam's "ignore all" collision setting and/or use Modrinth Edition.\* But it'll be difficult to _enforce_ this.

Currently Freecam doesn't interact with servers _at all_, so we don't have any way to know what config the server would prefer (or require). There is a separate feature request asking us to support a "permissions" protocol of some kind #105.

As for controversy; it is a philosophical question whether users or servers should be in control of what mods are installed locally and how they are configured. Personally, I'm open to giving servers more control, though I suspect a subset of users would not appreciate servers being able to override their config. I think us clearly notifying users stuff has been disabled and why would mitigate this though 🤔 

_\* Modrinth policies require us to force ignore-all to be disabled on non-op multiplayer servers._

**Comment by jinkhya** [comment] 2024-06-16 17:35
Thanks for the feedback and indeed it'd be impossible to enforce, nor do we really want players to feel like they're being constantly watched.

I agree it's probably going to annoy some players if their config gets overridden but I personnaly think, as a server  admin, if I explain to my community, your freecam config will be overridden to match the server to make sure everybody has the same chances whether or not you use freecam, I don't think anybody will complain. on the contrary. I'm sure there's also a subset of player who feel like the use of freecam underground to "scan" isn't fair. Explaining it this way is definitely better than saying, no freecam or you're banned as seen on some servers, which I also respect. Not here to tell anybody how to run their servers.
I have a feeling the people who would complain are the ones using it to take shortcuts underground tbh. 

I can also see people saying "well what if I want to find all the caves to torch it so nothing spawns". I would say "well in vanilla with no mods you wouldn't be able to either and our server is meant to be played the vanilla way". 

As you saw, my approach was not to say remove a feature but give the option for server owners to tweak it as they wish. Players can then choose to move to another server if they do not like the way it's setup. 

Btw I did try modrinth edition yesterday and it comes with `"ignoreTransparent": false`, `"ignoreOpenable": false,`, `"ignoreCustom": false` `"ignoreAll": true`. I think `ignoreAll` is at least supposed to be false by default?

**Comment by MattSturgeon** [comment] 2024-06-16 18:00
> If I explain to my community, your freecam config will be overridden to match the server to make sure everybody has the same chances whether or not you use freecam, I don't think anybody will complain. on the contrary.

I'm sure if we ever had proper support in freecam, we'd be able to have some kinda notification or summary screan.

I don't see an obvious way to solve this though. Nor am I able to work on it currently.

> Btw I did try modrinth edition yesterday and it comes with `"ignoreTransparent": false`, `"ignoreOpenable": false,`, `"ignoreCustom": false` `"ignoreAll": true`. I think `ignoreAll` is at least supposed to be false by default?

Modrinth Edition doesn't work by disabling the config setting itself, instead the implementation checks the config value _and also_ whether modrinth's conditions are met: https://github.com/MinecraftFreecam/Freecam/blob/1c13517f8fd52d2f7ce2ed76c759d112667b7b66/variant/modrinth/src/main/java/net/xolt/freecam/variant/impl/ModrinthBuild.java#L16-L18

All that changes in the config menu is some of the tooltips; these are tweaked to clarify the options won't work outside of singleplayer.

**Comment by MattSturgeon** [comment] 2024-06-16 18:02
I'll mark this as a duplicate of #105, as I think the overall goal is the same. Please sub to that issue and/or comment any additional context/suggestions there.

**Closed by MattSturgeon** 2024-06-16 18:02 UTC
Labels: enhancement

**Comment by jinkhya** [comment] 2024-06-16 18:43
Fair enough, a permission to allow / deny "cheats" would work perfectly.

To follow the comment about Modrinth edition, either I'm missing something or there's an issue with it. I setup a vanilla server with no modloader or any plugins. Joined with my client ( I'm not opped) with fabric+modrinth edition and I can use it underground.

**Comment by MattSturgeon** [comment] 2024-06-16 18:53
> To follow the comment about Modrinth edition, either I'm missing something or there's an issue with it. I setup a vanilla server with no modloader or any plugins. Joined with my client ( I'm not opped) with fabric+modrinth edition and I can use it underground.

Huh, that's concerning. Would you mind opening that as a new issue so I remember to investigate?

**Comment by jinkhya** [comment] 2024-06-16 19:04
Sure thing !
