### ISSUE TITLE
Incompatibility with First Person Model mod

### ISSUE THREAD

**Issue by AzuryxxVortex** [MinecraftFreecam/Freecam#203] opened 2024-04-29 00:24 UTC
### Description of the issue

When Freecam is activated with the [First Person Model](https://modrinth.com/mod/first-person-model) mod, a default skin is rendered, and it's made worse by it crawling for some reason-
![image](https://github.com/MinecraftFreecam/Freecam/assets/112041895/981a0a7e-8737-407e-9577-f1d4033afdbb)

I have reported the issue to said mod, but thought putting it here as well may be useful. Or not, I'm not sure. But here goes:

### Expected behavior

I expected no player model to render.. Kind of like this.
![image](https://github.com/MinecraftFreecam/Freecam/assets/112041895/87a121d6-2712-40ae-b406-2811f8e67a02)

### Steps to reproduce

1. Open a singleplayer world with both Freecam and First Person Model installed
2. Enable Freecam
3. Default player model renders, whilst it shouldn't

### Log output

```shell
No real need I believe.
```

### Crash report

```shell
No crash to report.
```

### How prevalent is the issue?

Always

### Freecam version

1.2.1

### Are you using "Modrinth Edition"?

Yes

### Minecraft version

1.20.1

### Modding platform

- [ ] Fabric
- [ ] Neoforge
- [X] Forge

**Comment by MattSturgeon** [comment] 2024-04-29 00:32
Duplicate of #185

**Closed by MattSturgeon** 2024-04-29 00:32 UTC
Labels: bug, unverified

**Comment by AzuryxxVortex** [comment] 2024-04-29 00:34
Oh, sorry about this then.
I'll look forward to it, thanks!
