### ISSUE TITLE
Freecam not rendering underground with Iris Shaders 1.7

### ISSUE THREAD

**Issue by betosalvestrini** [MinecraftFreecam/Freecam#205] opened 2024-04-29 18:52 UTC
### Description of the issue

whenever I try to see underground with freecam it does not render correctly
![2024-04-29_20 42 45](https://github.com/MinecraftFreecam/Freecam/assets/39284934/24c0dae1-e486-4b4c-bc3c-90b56a1941e4)

### Expected behavior

render the caves correctly

### Steps to reproduce

1. Open a singleplayer world
2. Enable Freecam by pressing `F4`
3. ...

### How prevalent is the issue?

always

### Freecam version

1.2.3

### Are you using "Modrinth Edition"?

Yes

### Minecraft version

1.20.4

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by MattSturgeon** [comment] 2024-04-30 06:07
Do you get this behaviour when Freecam is the only mod installed?

Do you also get this issue with the non-Modrinth version (GitHub or CurseForge)?

Would you mind listing what other mods you're using when you have this issue? In particular, mods that affect rendering could have compatibility issues.

**Comment by betosalvestrini** [comment] 2024-04-30 10:35
Do you get this behaviour when Freecam is the only mod installed?

- No, I managed to identify that this issue only occurs when using iris shaders mod

Do you also get this issue with the non-Modrinth version (GitHub or CurseForge)?

- Both version give the same results

Would you mind listing what other mods you're using when you have this issue? In particular, mods that affect rendering could have compatibility issues.

- here are the mods installed in this instance:

![Screenshot 2024-04-30 123256](https://github.com/MinecraftFreecam/Freecam/assets/39284934/d6a4554f-9188-4578-bf5c-e740dd48e129)

**Comment by MattSturgeon** [comment] 2024-04-30 15:16
Well done for identifying the issue! It sounds like somewhere between 1.6.17 and 1.7.0 Iris shaders has changed something to cause this.

I'd recommend opening an issue [over there](https://github.com/IrisShaders/Iris/issues) so that they're aware.

**Comment by devjta** [comment] 2024-05-12 10:20
> Do you get this behaviour when Freecam is the only mod installed?
> 
> * No, I managed to identify that this issue only occurs when using iris shaders mod 1.7
> 
> Do you also get this issue with the non-Modrinth version (GitHub or CurseForge)?
> 
> * Both version give the same results
> 
> Would you mind listing what other mods you're using when you have this issue? In particular, mods that affect rendering could have compatibility issues.
> 
> * here are the mods installed in this instance:
> 
> ![Screenshot 2024-04-30 123256](https://private-user-images.githubusercontent.com/39284934/326767122-d6a4554f-9188-4578-bf5c-e740dd48e129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDk0ODIsIm5iZiI6MTcxNTUwOTE4MiwicGF0aCI6Ii8zOTI4NDkzNC8zMjY3NjcxMjItZDZhNDU1NGYtOTE4OC00NTc4LWJmNWMtZTc0MGRkNDhlMTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEwMTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YTRjZGFiYmQ1ZmJiMWUzMmYwYzQ4ZTZkOGJmYjkwYjFlMWZlYjllOTY2YzU3YTg3NmI3ODRkM2E0NGVlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPe6kkvyCHMSrP03N6T3gsAhysuFPFtyDqBjBe9AYE4)
> 
> Update: freecam is working correctly with iris shaders version 1.6.17

Did you make a bug entry over there? That bug is really annoying. I have removed Iris for now.

**Comment by mrobaer** [comment] 2024-06-03 01:22
Using iris-1.7.0+mc1.20.6.jar with freecam-fabric-1.2.4+mc1.20.5.jar breaks Freecam for me as well.  Freecam will work with all other mods I have, but once I place the iris shaders mod back, most of the underground does not render.  It's unfortunate, because even disabling the shaders doesn't resolve it.

**Comment by tticehurst** [comment] 2024-06-14 18:03
can confirm happens on 1.21

**Comment by devjta** [comment] 2024-06-16 10:04
Just for info, with Tweakeroo freecam, it doenst happen: https://github.com/maruohon/tweakeroo
1.21 port: https://github.com/sakura-ryoko/tweakeroo/releases

Can use Iris 1.7.1 with it and see caves. Tried Freecam beta build yesterday, same issue.

**Comment by Longie520** [comment] 2024-07-30 04:01
Issue still persistent with Iris 1.7.3 and Freecam 1.3.0 for MC1.21

**Comment by Longie520** [comment] 2024-08-26 07:05
Issue still persists with Iris 1.8.0-beta.3+mc1.21.1 and Freecam 1.3.0+mc1.21
Version is 1.21.1 with Fabric 0.16.2

**Comment by beaver700nh** [comment] 2024-09-14 17:10
Can confirm same issue with same versions as Longie520 except Fabric 0.16.5
![2024-09-14_13 09 18](https://github.com/user-attachments/assets/d1db4512-fc02-4830-a99e-7d62aeb5a8b6)

**Comment by MebsUnderscore** [comment] 2024-10-01 11:55
Posting this here and also in the bug report for Iris bug 2321.
This rendering issue might be from a update to Minecraft itself, as when doing this testing, as with others, removing Iris from the mod folder fixes the issue.
But with Iris installed switching your game mode to spectator mode and go into freecam, this issue do not occur. And in Freecam mode, switching back to creative/survival/adventure makes everything go black again (except some tourches).

**Comment by ST-DDT** [comment] 2024-10-12 21:56
There is now a commit to iris that fixes the issue:

https://github.com/IrisShaders/Iris/issues/2321#issuecomment-2408638493

It isn't released yet, but you can use the GH build artifacts.

- https://github.com/IrisShaders/Iris/actions/runs/11307547568 -> [iris-artifacts](https://github.com/IrisShaders/Iris/actions/runs/11307547568/artifacts/2048915262) -> fabric

**Comment by Longie520** [comment] 2024-12-06 08:37
seems to have been fixed, as iris1.8.3 + freecam1.3.0 combined no longer reproduce the visual glitch.

**Comment by MattSturgeon** [comment] 2024-12-06 09:11
Thanks all for keeping this issue up to date. I'll close it now as it sounds like the upstream fix has made it into a release.

**Closed by MattSturgeon** 2024-12-06 09:11 UTC
Labels: bug, compatibility
