### ISSUE TITLE
[1.20.1 Forge] Control Modifiers (Shift/Ctrl/etc) No longer work correctly

### ISSUE THREAD

**Issue by Flexico** [MinecraftFreecam/Freecam#102] opened 2023-07-31 00:19 UTC
In MC 1.18.2, I set up the controls for Freecam to toggle on Ctrl+F5 and it worked as a separate action from F5, but after updating to 1.20.1, Freecam toggles regardless of whether Ctrl is held down. I play with a controller, so making use of modifier keys helps a lot when adding new controls from mods!

**Comment by MattSturgeon** [comment] 2023-12-31 14:19
Vanilla & fabric don't appear to allow setting a key to a modifier+key combo, so this will need special handling for the forge version.

I noticed on neoforge (assume the same for legacy forge) that setting a keybind to `Ctrl+F5` warns that those keys are bound to other actions. Was this also the case in older versions where keybinds worked as expected?

It's possible that this is an issue with forge rather than freecam, but I'd have to investigate further to be sure.

**Comment by MattSturgeon** [comment] 2024-02-05 07:42
Going to close this as it's a forge-specific feature and I don't think we'll get around to properly investigating whether the issue is on our end or theirs.

We may reconsider if someone can point us towards an upstream issue or relevant documentation on implementing the feature.

**Closed by MattSturgeon** 2024-02-05 07:42 UTC
Labels: bug
