### ISSUE TITLE
Chunk Generation ?

### ISSUE THREAD

**Issue by Hng-Vit** [MinecraftFreecam/Freecam#219] opened 2024-06-09 09:12 UTC
### Description of the issue

![image](https://github.com/MinecraftFreecam/Freecam/assets/145693819/b13febf0-93ad-40c8-80b9-2ce7163572a9)
cannot see caves under the player

### Expected behavior

to see all the caves and stuffs

### Steps to reproduce

1. Open a singleplayer world
2. Enable Freecam by pressing `F4`
3. Go underground 

### Freecam version

1.2.4

### Are you using "Modrinth Edition"?

No

### Minecraft version

1.20.6

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by Hng-Vit** [comment] 2024-06-09 09:13
![image](https://github.com/MinecraftFreecam/Freecam/assets/145693819/c88fbf37-8b7e-4ac9-90ec-df25de4699c6)
sorry for the wrong picture

**Comment by Hng-Vit** [comment] 2024-06-09 09:14
![Uploading image.png…]()

**Comment by MattSturgeon** [comment] 2024-06-09 09:30
Are you using Iris? This looks like this issue: https://github.com/IrisShaders/Iris/issues/2321

Also reported here as https://github.com/MinecraftFreecam/Freecam/issues/205

**Comment by MattSturgeon** [comment] 2024-06-11 01:45
I'm going to close this as a duplicate of #205.

Please re-open if you can verify you have a different issue.

**Closed by MattSturgeon** 2024-06-11 01:45 UTC
Labels: bug, unverified
