### ISSUE TITLE
Epic Fight is buggy when used together

### ISSUE THREAD

**Issue by 1936268516** [MinecraftFreecam/Freecam#209] opened 2024-05-05 15:13 UTC
### Description of the issue

When I return to my body after an out-of-body experience, it causes me to not be able to switch Epic Fight is modes only by dying or exiting.

### Steps to reproduce

1. Open a singleplayer world
2. Enable Freecam by pressing `F4`
3. ...

### How prevalent is the issue?

No way to switch modes so you can't play properly.

### Freecam version

Freecam1.2.1

### Are you using "Modrinth Edition"?

No

### Minecraft version

1.20.1

### Modding platform

- [ ] Fabric
- [ ] Neoforge
- [X] Forge

**Comment by MattSturgeon** [comment] 2024-05-05 16:04
I believe this is a duplicate of #113

**Closed by MattSturgeon** 2024-05-05 16:04 UTC
Labels: bug, unverified
