### ISSUE TITLE
Hide pumpkin overlay (etc)

### ISSUE THREAD

**Issue by frosthuuuund** [MinecraftFreecam/Freecam#239] opened 2024-07-26 13:13 UTC
### Description of the issue

Carved pumpkin overlay is still present when you on freecam mode.

### Expected behavior

I think freecam should prevent drawing any overlays

### Steps to reproduce

1. Login into world
2. Equip carved pumpkin on your head
3. Enter the freecam
4. Observe the bug

### Freecam version

v1.3.0-beta1

### Are you using "Modrinth Edition"?

Yes

### Minecraft version

1.21

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by MattSturgeon** [comment] 2024-07-26 13:25
We should probably handle this the same way as the "Show Submersion Fog" option.

Although maybe not, because the pumpkin overlay is caused by the player's inventory (head slot) while the submersion fog is caused by the _camera's_ location.

**Comment by hashalite** [comment] 2024-07-27 03:53
Fixed in next release

**Closed by hashalite** 2024-07-27 03:53 UTC
Labels: bug, unverified
